### PR TITLE
Travis: fix neovim

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
Vroom crashes.
Master branch is reported to be OK: https://github.com/google/vroom/issues/106

**Comment by dbarnett** [comment]
So update vroom release and then apply this, right? Why doesn't it need the `--allow-external sudo` anymore?

**Comment by dbarnett** [comment]
I checked the new vroom release on maktaba (google/vim-maktaba#214). The neovim tests still have preexisting issues causing them to hang (see google/vroom#83 and google/vroom#100), so even if they are currently passing here I'd leave the `allow_failures` override in place until that's fixed.

**Comment by blueyed** [comment]
> Why doesn't it need the --allow-external sudo anymore?

IIRC this options does not exist anymore, and caused pip to fail.

**Comment by blueyed** [comment]
Also mentioned in the commit message.
I've removed 135af1f.

**Comment by blueyed** [comment]
> You can update vroom version to 0.13.0, and then LGTM.

Done.

Unfortunately Neovim now appears to hang on a hit-enter prompt: https://github.com/encode/django-rest-framework/pull/6047/files#diff-b91f3d5bd63fcd17221b267e851608e8R33.

**Comment by dbarnett** [comment]
Right, mentioned that in an earlier comment. The other updates are useful in themselves, so just add the `allow_failures` override back and you can proceed w/ submitting.

**Comment by dbarnett** [comment]
LMK if you won't get around to updating and submitting this, and I can take over submitting the changes if so.

**Comment by blueyed** [comment]
@dbarnett 
Please take over.

**Comment by dbarnett** [comment]
Done, obsoleted this PR with my #38. Required a surprising number of small tweaks to get it working again.

**Pull request closed without merging**
