### PR TITLE
Use maktaba#python#Eval for Python 3 support

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by blueyed** [comment]
@googlebot 
I signed it!

**Comment by malcolmr** [comment]
You'll want to change `.travis.yml` and `plugin/coverage.vim` to update the minimum Maktaba version to at least 1.12.0 (was 1.9.0), since that's the version that added `maktaba#python#Eval`.

(1.14.0 was the version that added python3 support to `maktaba#python#`, but I don't think we need to explicitly test that version in addition - we're already testing against Maktaba master.)

**Comment by blueyed** [comment]
@malcolmr 
Thanks.  What about the comment there? (https://github.com/google/vim-coverage/blob/97ad576f3c29302fb9d9def698f3ebc50f6a3413/.travis.yml#L4)

**Comment by blueyed** [comment]
@malcolmr 
Thanks!
Please squash-merge it then - or should I force-push already?  (might save a build then, so I will do it)

**Pull request merged**
